swagger: '2.0'
schemes:
  - https
host: api.mediasmart.io
basePath: /
info:
  version: '1.4.1'
  title: Mediasmart
  termsOfService: 'https://mediasmart.io/terms-of-use/'
  contact:
    email: support@mediasmart.io
    url: 'https://mediasmart.io/contact/'
  # license:
  #  name: Apache 2.0
  #  url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://mediasmart.io/assets/images/logo-banner.jpg'
  description: |
    This is the **API reference** for [mediasmart.io](https://mediasmart.io), directly used by
    [our web application client](https://console.mediasmart.io) but also open to our customers. So using our API
    you'll be able to do most things you can do by mean of the web interface.

    Mediasmart API is private, so first of all you'll need to
    [register an account](http://mediasmart.io/pricing/?utm_source=mediasmart&utm_campaign=api-reference) in case
    you don't have one yet.

externalDocs:
  description: Learn more about us
  url: 'https://mediasmart.io/'
produces:
  - application/json
  - text/plain
  - text/csv
consumes:
  - application/json
  - multipart/form-data
tags:
  - name: dictionaries
    description: Available values in mediasmart platform
  - name: public
    description: Public operations. Authentication is not required.
  - name: analytics
    description: Performance and spending reports
  - name: User
    description: Operations about user

securityDefinitions:
  auth_token:
    description: Most of our API endpoints are private. Authentication is performed by mean of a token included in your
      `authorization` header. That token has to be generated by mean of a `[POST] /login` call.
    type: apiKey
    in: header
    name: authorization

responses:
  '400':
    description: Wrong request
    examples:
      application/json:
        message: Wrong request
  '401':
    description: Not authenticated
    examples:
      application/json:
        message: Authentication required. Token not provided.
  '403':
    description: Forbidden action
    examples:
      application/json:
        message: Invalid or expired token provided.
  '429':
    description: Quota exceeded
    examples:
      application/json:
        message: Requests per minute quota exceeded

definitions:
  CountriesList: &CountriesList
    type: string
    description: Country codes list (comma separated). Available values may depend on your account, so check `countries` dictionary to retrieve the full list.
    format: code1,code2,code3
    enum:
      - AFG
      - ALB
      - DZA
      - ASM
      - AND
      - AGO
      - AIA
      - ATA
      - ATG
      - ARG
      - ARM
      - ABW
      - AUS
      - AUT
      - AZE
      - BHS
      - BHR
      - BGD
      - BRB
      - BLR
      - BEL
      - BLZ
      - BEN
      - BMU
      - BTN
      - BOL
      - BIH
      - BWA
      - BVT
      - BRA
      - IOT
      - BRN
      - BGR
      - BFA
      - BDI
      - KHM
      - ...
  RegionsList: &RegionsList
    type: string
    description: Region codes list (comma separated). Available values may depend on your account, so check `regions` dictionary to retrieve the full list.
    format: code1,code2,code3
    enum:
      - FRA:F
      - FRA:P
      - ESP:GA
      - ESP:CM
      - ESP:AS
      - ESP:MD
      - ESP:RI
      - ESP:CE
  KPI: &KPI
    type: string
    description: Key Performance Indicator. Available values may depend on your account, so check `kpis` key in the dictionary to retrieve the full list.
    enum:
      - offers
      - bids
      - bidpercent
      - won
      - wonpercent
      - wonprice
      - impressions
      - clicks
      - ctr
      - events1
      - cr1
      - events2
      - cr2
      - events3
      - cr3
      - events4
      - cr4
      - events5
      - cr5
      - cpm
      - cpc
      - cpa1
      - cpa2
      - cpa3
      - cpa4
      - cpa5
      - cpvcomplete
      - cpvstart
      - videostart
      - videofirstquartile
      - videomidpoint
      - videothirdquartile
      - videocomplete
      - views
      - vr_start
      - vr_firstquartile
      - vr_midpoint
      - vr_thirdquartile
      - vr_complete
  Countries:
    type: object
    example:
      ESP: Spain
      FRA: France
      PRT: Portugal
      ...: ...
  Cities:
    type: object
    example:
      3121424: Gijón
      3110962: Sama
      3129135: Avilés
      3116789: Mieres
      3114711: Oviedo
      ...: ...
  Dictionary:
    type: object
    example:
      countries:
        ESP: Spain
        FRA: France
        PRT: Portugal
        ...: ...
      drilldown:
        campaign: Campaign
        exchange: Ad Exchange
        os: Operating system
        ...: ...
      kpis:
        offers: Bid offers
        bids: Bids
        impressions: Impressions
        clicks: Clicks
        ...: ...
      ...: ...
  timeline:
    type: object
    example:
      id1:
        '2018-05-03': 3234
        '2018-05-04': 3223
        '2018-05-05': 3001
        ...: ...
      id2:
        '2018-05-03': 32
        '2018-05-04': 433
        '2018-05-05': 0
        ...: ...
      ...: ...
  Regions:
    type: object
    example:
      ESP:GA: Galicia
      ESP:CM: Castille-La Mancha
      FRA:F: Centre
      FRA:P: Lower Normandy
      ...: ...
  Report:
    type: object
    example:
      - day: '2017-08-01'
        impressions: 12304
        clicks: 2349
        events1: 44
      - day: '2017-08-02'
        impressions: 40004
        clicks: 5049
        events1: 20
      - ...: ...
  Email:
    description: User email address
    type: string
    format: email
    example: john.smith@example.com
  User:
    type: object
    properties:
      id:
        $ref: '#/definitions/Identifier'
      token:
        description: Authorization token
        type: string
        minLength: 32
        maxLength: 32
        example: padyfwu23fkt6abxf3lfl5ao43sjxden
      username:
        description: User username
        type: string
        minLength: 1
        example: anexampleuser
      name:
        $ref: '#/definitions/Name'
      email:
        $ref: '#/definitions/Email'
      image:
        $ref: '#/definitions/Image'
      role:
        description: User role
        type: string
        minLength: 1
        example: 'editor'
  Identifier:
    description: Unique identifier
    type: string
    minLength: 16
    maxLength: 32
    example: eeeefwu98fkt6abxuytfl5ao43sjx767
  Image:
    description: Image URL
    type: string
    format: url
    example: http://d2wt9ed5gia51z.cloudfront.net/xxxxxxxxxxxxxxxx
  Name:
    description: A name for humans
    type: string
    example: This Is Just a Name
  State:
    description: State in the platform
    type: string
    example: active
  Organization:
    type: object
    properties:
      id:
        $ref: '#/definitions/Identifier'
      name:
        $ref: '#/definitions/Name'
      image:
        $ref: '#/definitions/Image'
      state:
        $ref: '#/definitions/State'
  Session:
    allOf:
      - $ref: '#/definitions/User'
      - type: object
        description: Authenticated session
        properties:
          organization:
            $ref: '#/definitions/Organization'
          users:
            type: array
            items:
              $ref: '#/definitions/User'
  Status:
    type: object
    properties:
      version:
        description: API gateway version
        type: string
        minLength: 5
        example: 1.3.17
      status:
        description: Global status
        type: string
        minLength: 1
        example: All servers are OK

paths:
  '/status':
    get:
      tags:
        - public
      summary: status
      description: This endpoint is usefull to check servers status. If a success response is returned it means our API is up. Additional information related to servers or services status may be included in the response.
      produces:
        - application/json
      responses:
        '200':
          description: The API is up
          schema:
            $ref: '#/definitions/Status'
        '429':
          description: Quota exceeded
          schema:
            $ref: '#/definitions/Status'
          examples:
            application/json:
              message: You've exceeded your requests per minute quota
  '/login':
    post:
      tags:
        - public
      summary: login
      description: Performs a login to retrieve a session including an authorization token. That token can be used as `authorization` header for later requests.
      consumes:
        - application/json
      parameters:
        - name: credentials
          in: body
          description: User credentials
          required: true
          schema:
            type: object
            properties:
              username:
                description: Username or email
                type: string
                minLength: 1
                example: thisismyusername
              password:
                description: Password
                type: string
                minLength: 1
                example: thisismypassword
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema: # response schema can be specified for each response
            $ref: '#/definitions/Session'
        '400':
          description: Wrong request
          examples:
            application/json:
              message: Wrong request
        '401':
          description: Not authenticated
          examples:
            application/json:
              message: Wrong credentials
        '429':
          description: Quota exceeded
          examples:
            application/json:
              message: You've exceeded your requests per minute quota

  '/api/dictionary':
    get:
      tags:
        - dictionaries
      summary: dictionary
      description: Retrieves the main dictionary, including all values for everything in our platform. From available
        campaign states to existing user roles.
      parameters:
        - name: authorization
          in: header
          description: Authorization token
          required: true
          type: string
      produces:
        - application/json
      security:
        - auth_token: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Dictionary'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '429':
          $ref: '#/responses/429'

  '/api/dictionary/countries':
    get:
      tags:
        - dictionaries
      summary: countries
      description: Retrieves all available countries for reporting or campaigns configuration
      parameters:
        - name: authorization
          in: header
          description: Authorization token
          required: true
          type: string
      produces:
        - application/json
      security:
        - auth_token: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Countries'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '429':
          $ref: '#/responses/429'

  '/api/dictionary/regions':
    get:
      tags:
        - dictionaries
      summary: regions
      description: Retrieves all available regions from specified countries list
      parameters:
        - name: authorization
          in: header
          description: Authorization token
          required: true
          type: string
        - name: countries
          in: query
          type: string
          <<: *CountriesList
      produces:
        - application/json
      security:
        - auth_token: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Regions'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '429':
          $ref: '#/responses/429'

  '/api/dictionary/cities':
    get:
      tags:
        - dictionaries
      summary: cities
      description: Retrieves all available cities from specified countries or regions list
      parameters:
        - name: authorization
          in: header
          description: Authorization token
          required: true
          type: string
        - name: countries
          in: query
          type: string
          <<: *CountriesList
        - name: regions
          in: query
          type: string
          <<: *RegionsList
      produces:
        - application/json
      security:
        - auth_token: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Cities'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '429':
          $ref: '#/responses/429'

  '/api/analytics/summary/{kpi}':
    get:
      security:
        - auth_token: []
      tags:
        - analytics
      summary: KPI timeline
      description: Retrieves a general view of the evolution of user's campaigns, during the last week, based on a provided KPI.
      parameters:
        - name: authorization
          in: header
          description: Authorization token
          required: true
          type: string
        - name: kpi
          required: true
          in: path
          <<: *KPI
        - name: campaigns
          in: query
          type: string
          format: id1,id2,id3
          description: Campaign identifiers (comma separated)
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: Success
          schema: # response schema can be specified for each response
            $ref: '#/definitions/timeline'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '429':
          $ref: '#/responses/429'

  '/api/analytics/custom-report':
    get:
      tags:
        - analytics
      summary: Custom report
      description: Computes a customized report, specifying drilldown variables, kpis and dates range.
      parameters:
        - name: authorization
          in: header
          description: Authorization token
          required: true
          type: string
        - name: from
          in: query
          description: Start date
          type: string
          format: YYYY-MM-DD
        - name: to
          in: query
          description: End date
          type: string
          format: YYYY-MM-DD
        - name: drilldown
          in: query
          type: string
          format: one,other,another
          description: Drilldown variables (comma separated)
        - name: kpis
          in: query
          type: string
          format: one,other,another
          description: KPIs (comma separated)
        - name: format
          in: query
          type: string
          format: json|csv|excel
          description: Output file format
        - name: raw
          in: query
          type: boolean
          format: true|false
          description: Active to avoid numbers rounding
        - name: rules
          in: query
          type: string
          format: variable1=[value1,value2];variable2!=[value3]
          description: Rules separated by semicolon.
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: Success
          schema: # response schema can be specified for each response
            $ref: '#/definitions/Report'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '429':
          $ref: '#/responses/429'
